### ISSUE TITLE
About the repository.

### ISSUE THREAD

**Issue by xinyu-site** [siyuzhou/SwarmRL#5]
Hi,

I am really interested in your work. I try to run the Swarmrl. But it seems like the code is not complete.
I cant find the environment BoidSphereEnv2D. How to fulfill the environment code?

Thanks!

**Comment by siyuzhou** [comment]
Hello,

Thank you for the interested in our work. This particular repository is not ready for full release yet. If you like to try it out, please check out the dependencies [SwarmNet](https://github.com/siyuzhou/swarmnet) and [Swarms](https://github.com/siyuzhou/swarms).
